services:

  db:
    image: postgres:17

    environment:
      POSTGRES_URL: ${DATABASE_URL}

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    environment:
      DATABASE_URL: ${POSTGRES_URL}

    depends_on:
      - db

  frontend:
    build:
      context: ./frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    environment:
      VITE_API_URL: http://localhost:8000

    depends_on:
      - backend

volumes:
  postgres_data: